-- ============================================================================
-- VOCABOLARIO DELLE MAESTRANZE — il repertorio dei mestieri che fanno un evento.
--
-- Criterio: c'è dentro chi LAVORA all'evento con le mani e col mestiere, non chi lo
-- vende. Il fotografo titolare è un FORNITORE; il suo secondo shooter è una MAESTRANZA.
-- Il catering è un fornitore; il cameriere di volante è una maestranza.
--
-- La famiglia è tassonomia INFORMATIVA (raggruppa per navigare 250+ voci), non un
-- ranking: nessun ordine di merito, nessun peso, nessun suggerimento.
--
-- Sono inclusi i mestieri della tradizione del Sud (organetto, zampogna, luminarie,
-- vara, pizzica) perché lì c'è il nostro territorio di partenza e perché sono lavoro
-- vero che nessuno censisce: è esattamente il "lavoro invisibile" del Rapporto.
-- ============================================================================

insert into public.maestranze_skills (name, famiglia, is_standard) values
  -- Sala e servizio ---------------------------------------------------------
  ('Maître','Sala e servizio',true),
  ('Capo sala','Sala e servizio',true),
  ('Cameriere di sala','Sala e servizio',true),
  ('Cameriere di banqueting','Sala e servizio',true),
  ('Commis di sala','Sala e servizio',true),
  ('Runner di sala','Sala e servizio',true),
  ('Addetto al buffet','Sala e servizio',true),
  ('Scalco / trinciante','Sala e servizio',true),
  ('Addetto guardaroba','Sala e servizio',true),
  ('Addetto office','Sala e servizio',true),
  ('Addetto lavaggio (plonge)','Sala e servizio',true),
  -- Cucina ------------------------------------------------------------------
  ('Executive chef','Cucina',true),
  ('Sous chef','Cucina',true),
  ('Chef de partie','Cucina',true),
  ('Capopartita','Cucina',true),
  ('Commis di cucina','Cucina',true),
  ('Aiuto cuoco','Cucina',true),
  ('Cuoco di banqueting','Cucina',true),
  ('Addetto show cooking','Cucina',true),
  ('Griglista','Cucina',true),
  ('Friggitore','Cucina',true),
  ('Cuoco per allergie e intolleranze','Cucina',true),
  ('Cuoco vegano e vegetariano','Cucina',true),
  ('Cuoco kosher','Cucina',true),
  ('Cuoco halal','Cucina',true),
  ('Pizzaiolo','Cucina',true),
  ('Fornaio / panificatore','Cucina',true),
  -- Pasticceria e dolci -----------------------------------------------------
  ('Pasticcere','Pasticceria e dolci',true),
  ('Aiuto pasticcere','Pasticceria e dolci',true),
  ('Cake designer','Pasticceria e dolci',true),
  ('Sugar artist','Pasticceria e dolci',true),
  ('Cioccolatiere','Pasticceria e dolci',true),
  ('Gelatiere','Pasticceria e dolci',true),
  ('Addetto crêpes e waffle','Pasticceria e dolci',true),
  ('Addetto confettata','Pasticceria e dolci',true),
  ('Montaggio torta nuziale','Pasticceria e dolci',true),
  -- Bar e miscelazione ------------------------------------------------------
  ('Barman','Bar e miscelazione',true),
  ('Bartender / mixologist','Bar e miscelazione',true),
  ('Flair bartender','Bar e miscelazione',true),
  ('Barback','Bar e miscelazione',true),
  ('Addetto open bar','Bar e miscelazione',true),
  ('Barista caffetteria','Bar e miscelazione',true),
  ('Barista specialty coffee','Bar e miscelazione',true),
  ('Sommelier','Bar e miscelazione',true),
  ('Sommelier di birra','Bar e miscelazione',true),
  ('Sommelier d''olio','Bar e miscelazione',true),
  ('Tea sommelier','Bar e miscelazione',true),
  -- Gastronomia da banco ----------------------------------------------------
  ('Tagliatore di prosciutto','Gastronomia da banco',true),
  ('Norcino','Gastronomia da banco',true),
  ('Casaro / carrello dei formaggi','Gastronomia da banco',true),
  ('Ostricaro','Gastronomia da banco',true),
  ('Addetto crudité di mare','Gastronomia da banco',true),
  ('Addetto sushi','Gastronomia da banco',true),
  ('Addetto street food','Gastronomia da banco',true),
  -- Fotografia --------------------------------------------------------------
  ('Secondo fotografo','Fotografia',true),
  ('Assistente fotografo','Fotografia',true),
  ('Fotografo di reportage','Fotografia',true),
  ('Fotografo ritrattista','Fotografia',true),
  ('Fotografo di still life','Fotografia',true),
  ('Assistente luci foto','Fotografia',true),
  ('Data manager / DIT','Fotografia',true),
  ('Ritoccatore fotografico','Fotografia',true),
  ('Addetto photobooth','Fotografia',true),
  ('Addetto photobooth 360','Fotografia',true),
  ('Addetto stampa istantanea','Fotografia',true),
  -- Video -------------------------------------------------------------------
  ('Videomaker','Video',true),
  ('Secondo operatore video','Video',true),
  ('Operatore steadicam','Video',true),
  ('Operatore gimbal','Video',true),
  ('Operatore drone (patentino ENAC)','Video',true),
  ('Fonico da presa diretta','Video',true),
  ('Assistente video','Video',true),
  ('Operatore multicamera','Video',true),
  ('Regista di evento','Video',true),
  ('Montatore video','Video',true),
  ('Colorist','Video',true),
  ('Operatore slow motion','Video',true),
  -- Musica ------------------------------------------------------------------
  ('DJ','Musica',true),
  ('Vocalist','Musica',true),
  ('Cantante solista','Musica',true),
  ('Cantante lirico','Musica',true),
  ('Cantante gospel','Musica',true),
  ('Corista','Musica',true),
  ('Coro gospel','Musica',true),
  ('Coro liturgico','Musica',true),
  ('Chitarrista','Musica',true),
  ('Chitarra classica','Musica',true),
  ('Bassista','Musica',true),
  ('Batterista','Musica',true),
  ('Percussionista','Musica',true),
  ('Pianista','Musica',true),
  ('Tastierista','Musica',true),
  ('Organista','Musica',true),
  ('Violinista','Musica',true),
  ('Violista','Musica',true),
  ('Violoncellista','Musica',true),
  ('Contrabbassista','Musica',true),
  ('Arpista','Musica',true),
  ('Flautista','Musica',true),
  ('Sassofonista','Musica',true),
  ('Trombettista','Musica',true),
  ('Trombonista','Musica',true),
  ('Fisarmonicista','Musica',true),
  ('Quartetto d''archi','Musica',true),
  ('Trio jazz','Musica',true),
  ('Band da matrimonio','Musica',true),
  ('Tribute band','Musica',true),
  ('Orchestra da ballo','Musica',true),
  ('Direttore musicale','Musica',true),
  -- Spettacolo --------------------------------------------------------------
  ('Presentatore / speaker','Spettacolo',true),
  ('Animatore','Spettacolo',true),
  ('Comico / cabarettista','Spettacolo',true),
  ('Illusionista / mago','Spettacolo',true),
  ('Mentalista','Spettacolo',true),
  ('Ballerino','Spettacolo',true),
  ('Coreografo','Spettacolo',true),
  ('Ballerini latino-americani','Spettacolo',true),
  ('Trampoliere','Spettacolo',true),
  ('Giocoliere','Spettacolo',true),
  ('Fire show / sputafuoco','Spettacolo',true),
  ('Acrobata aereo (tessuti)','Spettacolo',true),
  ('Contorsionista','Spettacolo',true),
  ('Statua vivente','Spettacolo',true),
  ('Mimo','Spettacolo',true),
  ('Caricaturista','Spettacolo',true),
  ('Sand artist','Spettacolo',true),
  ('Light painter','Spettacolo',true),
  ('Bolle di sapone giganti','Spettacolo',true),
  ('LED show / robot luminosi','Spettacolo',true),
  ('Sosia / imitatore','Spettacolo',true),
  -- Tradizione popolare -----------------------------------------------------
  ('Organettista','Tradizione popolare',true),
  ('Suonatore di tamburello','Tradizione popolare',true),
  ('Chitarra battente','Tradizione popolare',true),
  ('Zampognaro','Tradizione popolare',true),
  ('Ciaramellaro','Tradizione popolare',true),
  ('Cantore a braccio','Tradizione popolare',true),
  ('Gruppo folk','Tradizione popolare',true),
  ('Ballerini di tarantella','Tradizione popolare',true),
  ('Ballerini di pizzica','Tradizione popolare',true),
  ('Sbandieratore','Tradizione popolare',true),
  ('Tamburino','Tradizione popolare',true),
  ('Banda musicale','Tradizione popolare',true),
  ('Luminarista','Tradizione popolare',true),
  ('Fuochista di festa patronale','Tradizione popolare',true),
  ('Portatore di vara','Tradizione popolare',true),
  -- Tecnica audio, luci, video ----------------------------------------------
  ('Fonico','Tecnica audio, luci, video',true),
  ('Fonico di sala (FOH)','Tecnica audio, luci, video',true),
  ('Fonico di palco (monitor)','Tecnica audio, luci, video',true),
  ('Tecnico audio','Tecnica audio, luci, video',true),
  ('Light designer','Tecnica audio, luci, video',true),
  ('Datore luci','Tecnica audio, luci, video',true),
  ('Operatore luci','Tecnica audio, luci, video',true),
  ('Tecnico video','Tecnica audio, luci, video',true),
  ('VJ','Tecnica audio, luci, video',true),
  ('Operatore ledwall','Tecnica audio, luci, video',true),
  ('Operatore proiezioni / mapping','Tecnica audio, luci, video',true),
  ('Backliner','Tecnica audio, luci, video',true),
  ('Rigger','Tecnica audio, luci, video',true),
  ('Stage manager','Tecnica audio, luci, video',true),
  ('Stagehand / facchino di palco','Tecnica audio, luci, video',true),
  ('Elettricista di scena','Tecnica audio, luci, video',true),
  ('Generatorista','Tecnica audio, luci, video',true),
  ('Cablatore','Tecnica audio, luci, video',true),
  -- Effetti speciali --------------------------------------------------------
  ('Pirotecnico (patentino)','Effetti speciali',true),
  ('Addetto fuochi d''artificio','Effetti speciali',true),
  ('Operatore fontane luminose','Effetti speciali',true),
  ('Operatore macchina del fumo / CO2','Effetti speciali',true),
  ('Addetto sparacoriandoli','Effetti speciali',true),
  ('Addetto fuochi freddi','Effetti speciali',true),
  ('Tecnico effetti scenici','Effetti speciali',true),
  -- Allestimento e scenografia ----------------------------------------------
  ('Allestitore','Allestimento e scenografia',true),
  ('Scenografo','Allestimento e scenografia',true),
  ('Wedding designer','Allestimento e scenografia',true),
  ('Table designer','Allestimento e scenografia',true),
  ('Addetto mise en place','Allestimento e scenografia',true),
  ('Falegname di scena','Allestimento e scenografia',true),
  ('Tappezziere','Allestimento e scenografia',true),
  ('Montatore tensostrutture','Allestimento e scenografia',true),
  ('Montatore gazebo','Allestimento e scenografia',true),
  ('Montatore palchi e pedane','Allestimento e scenografia',true),
  ('Addetto sedute e tavoli','Allestimento e scenografia',true),
  ('Addetto tovagliato','Allestimento e scenografia',true),
  ('Calligrafo','Allestimento e scenografia',true),
  ('Balloon artist','Allestimento e scenografia',true),
  ('Addetto luminarie decorative','Allestimento e scenografia',true),
  ('Addetto candele','Allestimento e scenografia',true),
  ('Addetto insegne e cartellonistica','Allestimento e scenografia',true),
  -- Fiori e verde -----------------------------------------------------------
  ('Fiorista','Fiori e verde',true),
  ('Aiuto fiorista','Fiori e verde',true),
  ('Flower designer','Fiori e verde',true),
  ('Addetto composizioni floreali','Fiori e verde',true),
  ('Giardiniere','Fiori e verde',true),
  ('Addetto piante e verde','Fiori e verde',true),
  -- Bellezza ----------------------------------------------------------------
  ('Make-up artist','Bellezza',true),
  ('Assistente make-up','Bellezza',true),
  ('Hair stylist','Bellezza',true),
  ('Acconciatore','Bellezza',true),
  ('Barbiere','Bellezza',true),
  ('Onicotecnica','Bellezza',true),
  ('Estetista','Bellezza',true),
  ('Truccatore effetti speciali','Bellezza',true),
  ('Body painter','Bellezza',true),
  ('Henné artist','Bellezza',true),
  -- Abito e sartoria --------------------------------------------------------
  ('Sarto per ritocchi','Abito e sartoria',true),
  ('Vestizione sposa','Abito e sartoria',true),
  ('Modista (cappelli)','Abito e sartoria',true),
  ('Stiratrice','Abito e sartoria',true),
  ('Calzolaio','Abito e sartoria',true),
  ('Addetto noleggio abiti','Abito e sartoria',true),
  -- Cerimonia ---------------------------------------------------------------
  ('Celebrante laico','Cerimonia',true),
  ('Cerimoniere','Cerimonia',true),
  ('Officiante','Cerimonia',true),
  ('Lettore','Cerimonia',true),
  ('Interprete LIS','Cerimonia',true),
  ('Interprete e traduttore','Cerimonia',true),
  ('Addetto libretti messa','Cerimonia',true),
  ('Addetto riso e petali','Cerimonia',true),
  -- Accoglienza e ospitalità ------------------------------------------------
  ('Hostess di accoglienza','Accoglienza e ospitalità',true),
  ('Addetto welcome desk','Accoglienza e ospitalità',true),
  ('Addetto guest list','Accoglienza e ospitalità',true),
  ('Addetto tableau e segnaposto','Accoglienza e ospitalità',true),
  ('Concierge di evento','Accoglienza e ospitalità',true),
  ('Valet / parcheggiatore','Accoglienza e ospitalità',true),
  ('Addetto bagagli','Accoglienza e ospitalità',true),
  -- Bambini -----------------------------------------------------------------
  ('Baby sitter di evento','Bambini',true),
  ('Animatore per bambini','Bambini',true),
  ('Truccabimbi','Bambini',true),
  ('Addetto gonfiabili','Bambini',true),
  ('Addetto area bimbi / ludoteca','Bambini',true),
  -- Animali -----------------------------------------------------------------
  ('Dog sitter di evento','Animali',true),
  ('Pet concierge','Animali',true),
  ('Addestratore per cerimonia','Animali',true),
  -- Sicurezza e salute ------------------------------------------------------
  ('Addetto sicurezza','Sicurezza e salute',true),
  ('Steward di sicurezza','Sicurezza e salute',true),
  ('Buttafuori','Sicurezza e salute',true),
  ('Guardia giurata','Sicurezza e salute',true),
  ('Addetto antincendio','Sicurezza e salute',true),
  ('Soccorritore','Sicurezza e salute',true),
  ('Infermiere di evento','Sicurezza e salute',true),
  ('Medico di evento','Sicurezza e salute',true),
  -- Trasporti e logistica ---------------------------------------------------
  ('Autista NCC','Trasporti e logistica',true),
  ('Autista navetta','Trasporti e logistica',true),
  ('Autista mezzi pesanti','Trasporti e logistica',true),
  ('Facchino','Trasporti e logistica',true),
  ('Trasportatore allestimenti','Trasporti e logistica',true),
  ('Addetto carico e scarico','Trasporti e logistica',true),
  ('Magazziniere di evento','Trasporti e logistica',true),
  -- Pulizie e ripristino ----------------------------------------------------
  ('Addetto pulizie durante evento','Pulizie e ripristino',true),
  ('Addetto pulizie post evento','Pulizie e ripristino',true),
  ('Addetto bagni mobili','Pulizie e ripristino',true),
  ('Addetto raccolta differenziata','Pulizie e ripristino',true),
  ('Lavanderia e stireria','Pulizie e ripristino',true),
  -- Digital e streaming -----------------------------------------------------
  ('Operatore live streaming','Digital e streaming',true),
  ('Regista live','Digital e streaming',true),
  ('Social media manager di evento','Digital e streaming',true),
  ('Content creator / reel','Digital e streaming',true),
  ('Addetto app e QR evento','Digital e streaming',true),
  ('Addetto realtà virtuale','Digital e streaming',true),
  -- Coordinamento -----------------------------------------------------------
  ('Assistente wedding planner','Coordinamento',true),
  ('Coordinatore di sala','Coordinamento',true),
  ('Coordinatore di evento','Coordinamento',true),
  ('Responsabile di produzione','Coordinamento',true),
  ('Runner di produzione','Coordinamento',true)
on conflict (name) do update set famiglia = excluded.famiglia, is_standard = true;

do $$
declare v_n int; v_f int;
begin
  select count(*), count(distinct famiglia) into v_n, v_f from public.maestranze_skills;
  raise notice 'vocabolario maestranze: % mestieri in % famiglie', v_n, v_f;
end $$;
