-- 6 articoli (2 Gisko + 4 DaisyLab) dai post Instagram reali, con cover come hero.
insert into blog_posts (author_id, category_id, slug, title, excerpt, body_html, tags, status, seo_title, seo_description, reading_minutes, published_at)
select '1d0177ba-bfd9-4e2e-a997-7201f9273d55'::uuid, (select id from blog_categories where slug='storie'), 'andrea-federica-villa-ventura-gisko',
 $t$Andrea e Federica a Villa Ventura: un matrimonio da incorniciare$t$, $e$Un sorriso vero, Villa Ventura e una squadra affiatata: il racconto del matrimonio di Andrea e Federica in Calabria.$e$, $b$<p>Ci sono matrimoni che vorresti incorniciare per intero. Quello di Andrea e Federica e stato uno di questi.</p><h2>Il valore di un vero sorriso</h2><p>Dovremmo ritrovarci ancora di piu in un sorriso autentico: e li che vive l’emozione vera, ed e quello che cerco quando racconto una giornata. Niente pose forzate, solo cio che accade.</p><h2>Villa Ventura come cornice</h2><p>La cornice di Villa Ventura ha fatto il resto: eleganza, luce e quell’atmosfera calabrese che rende ogni scatto un piccolo quadro.</p><h2>Un giorno fatto da una squadra</h2><p>Un matrimonio da incorniciare non lo fa una persona sola. Grazie a chi ha collaborato: video Michele Belsito, hair Pino Cerra, make-up Martissima, fiori Flower Art, abito Mondo Sposa Vibo e Villa Ventura.</p><p><em>Vi sposate in Calabria e volete un racconto sincero del vostro giorno? Scriviamoci.</em></p>$b$, array['matrimonio Calabria','Villa Ventura','fotografo matrimonio','reportage'], 'PUBLISHED', $st$Matrimonio a Villa Ventura, Calabria | Gisko$st$, $sd$Il racconto del matrimonio di Andrea e Federica a Villa Ventura. Reportage di Gisko, fotografo in Calabria.$sd$, 3, now()
where not exists (select 1 from blog_posts where slug='andrea-federica-villa-ventura-gisko')
  and exists (select 1 from profiles where id = '1d0177ba-bfd9-4e2e-a997-7201f9273d55'::uuid);
update blog_posts set hero_image_url='https://zfwlkvqxfzvubmfyxofs.supabase.co/storage/v1/object/public/blog-media/daisy/DLVUGLgIDm9/cover.jpg' where slug='andrea-federica-villa-ventura-gisko';
insert into blog_posts (author_id, category_id, slug, title, excerpt, body_html, tags, status, seo_title, seo_description, reading_minutes, published_at)
select '1d0177ba-bfd9-4e2e-a997-7201f9273d55'::uuid, (select id from blog_categories where slug='storie'), 'matrimonio-sincero-elegante-lamezia-gisko',
 $t$Il matrimonio che piace a me: sincero, elegante, pieno di emozioni$t$, $e$Sincero, elegante, pieno di emozioni: un matrimonio alla Tenuta delle Grazie, Lamezia Terme.$e$, $b$<p>Finalmente un po’ di tempo per raccontare un matrimonio come quelli che piacciono a me: bello, sincero, espressivo, elegante, discreto e pieno di emozioni.</p><h2>Eleganza discreta</h2><p>Non servono eccessi per emozionare. Bastano persone vere, una luce giusta e la voglia di esserci senza disturbare. E cosi che lavoro: in punta di piedi, lasciando che la storia accada.</p><h2>Alla Tenuta delle Grazie, Lamezia Terme</h2><p>La Tenuta delle Grazie ha offerto lo scenario perfetto per un matrimonio raffinato e autentico, nel cuore della Calabria.</p><h2>Grazie alla rete di professionisti</h2><p>Un grazie a chi ha preso parte: i colleghi fotografi, video Severini Studio, make-up Tetyana, hair Pino Cerra, fiori Tahiti Fiori, abito Corso Mazzini Sposa.</p><p><em>Cercate un fotografo che racconti, non che metta in posa? Partiamo dalla vostra storia.</em></p>$b$, array['matrimonio Calabria','Lamezia Terme','fotografo matrimonio','Tenuta delle Grazie'], 'PUBLISHED', $st$Matrimonio a Lamezia Terme, Tenuta delle Grazie | Gisko$st$, $sd$Un matrimonio sincero ed elegante alla Tenuta delle Grazie, Lamezia Terme. Reportage di Gisko.$sd$, 3, now()
where not exists (select 1 from blog_posts where slug='matrimonio-sincero-elegante-lamezia-gisko')
  and exists (select 1 from profiles where id = '1d0177ba-bfd9-4e2e-a997-7201f9273d55'::uuid);
update blog_posts set hero_image_url='https://zfwlkvqxfzvubmfyxofs.supabase.co/storage/v1/object/public/blog-media/daisy/DLF5ra3IhvL/cover.jpg' where slug='matrimonio-sincero-elegante-lamezia-gisko';
insert into blog_posts (author_id, category_id, slug, title, excerpt, body_html, tags, status, seo_title, seo_description, reading_minutes, published_at)
select '1d5b5670-1e36-43a5-9219-d680f01ad889'::uuid, (select id from blog_categories where slug='ispirazioni'), 'ceralacca-partecipazioni-eleganza-daisylab',
 $t$La ceralacca: eleganza senza tempo per le tue partecipazioni$t$, $e$Storia ed eleganza della ceralacca, e perche la amo nelle partecipazioni fatte a mano.$e$, $b$<p>Vi presento la nuova gamma di colori per la ceralacca — e quanto li amo.</p><h2>Un materiale prezioso, con una storia antica</h2><p>La ceralacca si usa per sigillare e autenticare documenti e oggetti preziosi sin dal 3000 a.C.: in origine una miscela di resina, cera e pigmenti per creare un sigillo decorativo e funzionale. Nel tempo si e arricchita di gommalacca e resina di lacca, migliorando qualita e durata.</p><h2>Perche la amo nelle mie creazioni</h2><p>Oggi ha soprattutto uno scopo decorativo, ma porta con se secoli di significato: autenticita, cura, valore. Per questo la inserisco nei miei coordinati — un sigillo racconta che quell’invito e unico, pensato per voi.</p><h2>L’eleganza senza tempo</h2><p>Spesso, parlando con le coppie, mi accorgo che questa eleganza va spiegata: una volta vista dal vivo, pero, conquista. E tu, che colori preferisci?</p><p><em>Vuoi un coordinato con un tocco di ceralacca, cucito sulla vostra storia? Parliamone.</em></p>$b$, array['ceralacca','partecipazioni','wedding stationery','fatto a mano'], 'PUBLISHED', $st$Ceralacca per partecipazioni di matrimonio | DaisyLab_21$st$, $sd$La storia e l'eleganza della ceralacca nelle partecipazioni fatte a mano di DaisyLab_21.$sd$, 3, now()
where not exists (select 1 from blog_posts where slug='ceralacca-partecipazioni-eleganza-daisylab')
  and exists (select 1 from profiles where id = '1d5b5670-1e36-43a5-9219-d680f01ad889'::uuid);
update blog_posts set hero_image_url='https://zfwlkvqxfzvubmfyxofs.supabase.co/storage/v1/object/public/blog-media/daisy/DIy5Mo2IV7o/cover.jpg' where slug='ceralacca-partecipazioni-eleganza-daisylab';
insert into blog_posts (author_id, category_id, slug, title, excerpt, body_html, tags, status, seo_title, seo_description, reading_minutes, published_at)
select '1d5b5670-1e36-43a5-9219-d680f01ad889'::uuid, (select id from blog_categories where slug='ispirazioni'), 'scatoline-nascita-fatte-a-mano-daisylab',
 $t$Scatoline nascita fatte a mano: un angolo d’amore per il ritorno a casa$t$, $e$Scatoline confetti fatte a mano per il ritorno a casa di Gaia: dolcezza in ogni dettaglio.$e$, $b$<p>Qualche mese fa e nata Gaia. Insieme alla sua mamma abbiamo pensato a delle scatoline confetti dolci e tenere, con un coniglietto rosa protagonista di tutto il set allestito per il suo arrivo a casa.</p><h2>Il ritorno a casa, un momento magico</h2><p>Il rientro dall’ospedale e sempre speciale per mamma e papa: trovare un piccolo angolo dedicato all’amore appena nato rende quell’attimo ancora piu prezioso.</p><h2>Fatto a mano, pensato su misura</h2><p>Ogni dettaglio — dalle scatoline al coniglietto — e realizzato a mano e coordinato, perche anche i confetti raccontino la stessa storia di dolcezza.</p><p>Buona vita, piccola Gaia.</p><p><em>Aspettate un lieto evento e volete un set nascita personalizzato? Scrivetemi.</em></p>$b$, array['nascita','scatoline confetti','fatto a mano','newborn'], 'PUBLISHED', $st$Scatoline nascita fatte a mano | DaisyLab_21$st$, $sd$Set nascita coordinati e scatoline confetti fatte a mano da DaisyLab_21.$sd$, 3, now()
where not exists (select 1 from blog_posts where slug='scatoline-nascita-fatte-a-mano-daisylab')
  and exists (select 1 from profiles where id = '1d5b5670-1e36-43a5-9219-d680f01ad889'::uuid);
update blog_posts set hero_image_url='https://zfwlkvqxfzvubmfyxofs.supabase.co/storage/v1/object/public/blog-media/daisy/DHvzZ8vIBnX/cover.jpg' where slug='scatoline-nascita-fatte-a-mano-daisylab';
insert into blog_posts (author_id, category_id, slug, title, excerpt, body_html, tags, status, seo_title, seo_description, reading_minutes, published_at)
select '1d5b5670-1e36-43a5-9219-d680f01ad889'::uuid, (select id from blog_categories where slug='ispirazioni'), 'giuseppe-rossana-coordinato-bianco-rosa-daisylab',
 $t$Giuseppe e Rossana: un coordinato elegantissimo, bianco e rosa$t$, $e$Bianco e rosa, elegantissimo: il coordinato fatto a mano per Giuseppe e Rossana.$e$, $b$<p>Giuseppe e Rossana: un tripudio di bianco e rosa, elegantissimo.</p><h2>Bianco e rosa, l’eleganza che non stanca</h2><p>Una palette delicata, lavorata con cura in ogni pezzo del coordinato: partecipazioni, tableau, dettagli. Quando i colori dialogano, l’insieme respira raffinatezza.</p><h2>Tutto fatto a mano</h2><p>Ogni elemento e realizzato a mano, perche il coordinato di un matrimonio non e un dettaglio qualsiasi: e la prima impressione che resta nel ricordo degli invitati.</p><p><em>Volete un coordinato elegante e su misura per il vostro giorno? Progettiamolo insieme.</em></p>$b$, array['partecipazioni matrimonio','coordinato grafico','fatto a mano','Calabria'], 'PUBLISHED', $st$Coordinato matrimonio bianco e rosa | DaisyLab_21$st$, $sd$Un coordinato grafico elegantissimo, bianco e rosa, fatto a mano per Giuseppe e Rossana.$sd$, 3, now()
where not exists (select 1 from blog_posts where slug='giuseppe-rossana-coordinato-bianco-rosa-daisylab')
  and exists (select 1 from profiles where id = '1d5b5670-1e36-43a5-9219-d680f01ad889'::uuid);
update blog_posts set hero_image_url='https://zfwlkvqxfzvubmfyxofs.supabase.co/storage/v1/object/public/blog-media/daisy/C8KV9ByoX6y/cover.jpg' where slug='giuseppe-rossana-coordinato-bianco-rosa-daisylab';
insert into blog_posts (author_id, category_id, slug, title, excerpt, body_html, tags, status, seo_title, seo_description, reading_minutes, published_at)
select '1d5b5670-1e36-43a5-9219-d680f01ad889'::uuid, (select id from blog_categories where slug='ispirazioni'), 'raffaella-gregorio-partecipazioni-retro-daisylab',
 $t$Raffaella e Gregorio: partecipazioni retro, eleganti e piene di vita$t$, $e$Partecipazioni retro, carta semitrasparente e nastro in seta: l’invito di Raffaella e Gregorio.$e$, $b$<p>Raffaella e Gregorio. Nella semplicita delle loro persone e del loro matrimonio, abbiamo realizzato insieme partecipazioni colorate, eleganti e con un tocco retro.</p><h2>Dettagli che raccontano</h2><p>L’effetto strappato, i loro fiori stampati su una carta semitrasparente opaca, il nastro in seta azzurro polvere: ogni dettaglio incornicia l’invito del giorno piu emozionante della loro vita.</p><h2>Una storia di famiglia</h2><p>Il tutto arricchito dalla presenza del piccolo Rocco, che guardera i suoi genitori dirsi “si” e che ricevera il Battesimo nello stesso giorno. Una doppia festa, un solo grande amore.</p><p><em>Anche la vostra storia merita un invito che la racconti. Parliamone.</em></p>$b$, array['partecipazioni matrimonio','retro','fatto a mano','wedding stationery'], 'PUBLISHED', $st$Partecipazioni retro fatte a mano | DaisyLab_21$st$, $sd$Partecipazioni colorate e retro, carta semitrasparente e nastro in seta, fatte a mano da DaisyLab_21.$sd$, 3, now()
where not exists (select 1 from blog_posts where slug='raffaella-gregorio-partecipazioni-retro-daisylab')
  and exists (select 1 from profiles where id = '1d5b5670-1e36-43a5-9219-d680f01ad889'::uuid);
update blog_posts set hero_image_url='https://zfwlkvqxfzvubmfyxofs.supabase.co/storage/v1/object/public/blog-media/daisy/C5IxO9lovCE/cover.jpg' where slug='raffaella-gregorio-partecipazioni-retro-daisylab';
